const nomes = [
  'Jerlis',
  'Beatriz_ll',
  'Carmosadasilva',
  'Suzieandre',
  'Madalena',
  'Luana.sousa.98229',
  'gleycehellensantoscostas',
  'Keillagomessilva',
  'Cassiane_lima_2310',
  'Tatianesilvanava2',
  '_cleisasiqueira',
  'eligolveia',
  'sandrafontinele2',
  'miriamnandes',
  'taynarabarbosa60',
  'kelynavalima',
  'santos_kelly56',
  'biamattosofficial',
  'rosangelasilva5766',
  'gi_nino',
  'mixstoreoficial',
  'limap4419',
  'polinne14',
  'juniior_silvah7',
  'genilda_silva88',
  'regi.na983',
  'vanda_rb.gomes',
  'noeliasilva02kk',
  'sarah.menezws52',
  'alinnemarquess',
  'hiedanascimentonascimento',
  'silvana2015coimbra'
];

export default nomes;